Add missing dependency for GTK
Without this package, loading gtk fails with:
[pywebview] GTK cannot be loaded
Traceback (most recent call last):
  File "/home/dan/Documents/pywebview_ws/pywebview/webview/guilib.py", line 16, in import_gtk
    import webview.platforms.gtk as guilib
  File "/home/dan/Documents/pywebview_ws/pywebview/webview/platforms/gtk.py", line 25, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'