Update __init__.py
When webview.load_css(css, child_uid)  it's used, the interpreter throws:

TypeError: evaluate_js() missing 1 required positional argument: 'uid'

With this change the program already works.